# Generated by Django 4.1.7 on 2023-03-29 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_description', models.TextField(default='#', max_length=200)),
                ('field_pic', models.CharField(default='#', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_text', models.TextField()),
                ('field_objId', models.CharField(max_length=200, null=True)),
                ('field_tag', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_title', models.CharField(max_length=200)),
                ('field_objId', models.CharField(max_length=200, null=True)),
                ('field_description', models.TextField(blank=True, null=True)),
                ('field_createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TeachCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_description', models.TextField(max_length=200)),
                ('field_pic', models.CharField(default='#', max_length=200)),
                ('course_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.coursecatalog')),
            ],
        ),
        migrations.CreateModel(
            name='TeachCourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_description', models.TextField(max_length=200, null=True)),
                ('field_fileId', models.CharField(max_length=200, null=True)),
                ('teach_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.teachcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_text', models.CharField(max_length=200)),
                ('field_is_correct', models.BooleanField(default=False)),
                ('field_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.question')),
            ],
        ),
    ]
