# Generated by Django 4.1.7 on 2023-03-10 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseCatalogName', models.CharField(max_length=200)),
                ('description', models.TextField(default='#', max_length=200)),
                ('catalog_button', models.CharField(default='#', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeachCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeachCourseName', models.CharField(max_length=200)),
                ('teach_description', models.TextField(max_length=200)),
                ('teachOfpic', models.CharField(default='#', max_length=200)),
                ('course_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.coursecatalog')),
            ],
        ),
        migrations.CreateModel(
            name='TeachCourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitName', models.CharField(max_length=200)),
                ('unit_description', models.TextField(max_length=200, null=True)),
                ('fileId', models.CharField(max_length=200, null=True)),
                ('teach_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.teachcourse')),
            ],
        ),
    ]
