# Generated by Django 4.1.7 on 2023-03-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecatalog',
            old_name='catalog_button',
            new_name='catalogOfpic',
        ),
    ]
