# Generated by Django 4.1.7 on 2023-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='field_tag',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='field_tag',
            field=models.JSONField(default=list),
        ),
    ]
