# Generated by Django 4.1.7 on 2023-03-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_quiz_field_tag_alter_question_field_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='field_questionList',
            field=models.JSONField(default=list),
        ),
    ]
