# Generated by Django 4.1.7 on 2023-03-22 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_quiz_quizid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
