# Generated by Django 4.1.7 on 2023-03-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_quiz_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='pub_date',
            new_name='createDate',
        ),
    ]
