# Generated by Django 4.1.7 on 2023-03-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_rename_pub_date_quiz_createdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
    ]
