# Generated by Django 4.1.7 on 2023-03-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_question_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quesitonId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
