# Generated by Django 4.1.7 on 2023-03-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0009_question_quesitonid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesitonId',
            new_name='questionId',
        ),
    ]
